#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Added OAIStatRules table"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2282a9625084'
down_revision = '8f2b0c2109b1'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oarepo_oai_stat_rule',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('code', sa.String(length=16), nullable=False),
                    sa.Column('description', sa.String(length=2048), nullable=True),
                    sa.Column('result', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_oarepo_oai_stat_rule')),
                    sa.UniqueConstraint('code', name=op.f('uq_oarepo_oai_stat_rule_code'))
                    )
    op.create_table('oarepo_oai_provider_stat_rules',
                    sa.Column('provider_id', sa.Integer(), nullable=True),
                    sa.Column('stat_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['provider_id'], ['oarepo_oai_provider.id'], name=op.f(
                        'fk_oarepo_oai_provider_stat_rules_provider_id_oarepo_oai_provider')),
                    sa.ForeignKeyConstraint(['stat_id'], ['oarepo_oai_stat_rule.id'], name=op.f(
                        'fk_oarepo_oai_provider_stat_rules_stat_id_oarepo_oai_stat_rule'))
                    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_oarepo_oai_mapper_address'), 'oarepo_oai_mapper', type_='unique')
    op.drop_table('oarepo_oai_provider_stat_rules')
    op.drop_table('oarepo_oai_stat_rule')
    # ### end Alembic commands ###
