#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Removed entrypoint from OAIRule and OAIParser"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '24445d202733'
down_revision = '58b215455f1e'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite drop collumn: https://stackoverflow.com/questions/30394222/why-flask-migrate-cannot
    # -upgrade-when-drop-column
    # SQLite drop collumn: https://alembic.sqlalchemy.org/en/latest/batch.html
    with op.batch_alter_table("oarepo_oai_parser") as batch_op:
        batch_op.drop_column('entry_point')
    with op.batch_alter_table("oarepo_oai_rule") as batch_op:
        batch_op.drop_column('entry_point')
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oarepo_oai_rule',
                  sa.Column('entry_point', sa.VARCHAR(length=256), nullable=True))
    op.add_column('oarepo_oai_parser',
                  sa.Column('entry_point', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
