#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Add constant_field to OAIProvider"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c0ec46a1283'
down_revision = '5ffdbb78795e'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(op.f('uq_oarepo_oai_mapper_address'), 'oarepo_oai_mapper',
    #                             ['address'])
    op.add_column('oarepo_oai_provider', sa.Column('constant_fields', sa.JSON().with_variant(
        sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(
        postgresql.JSONB(none_as_null=True), 'postgresql').with_variant(
        sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oarepo_oai_provider', 'constant_fields')
    op.drop_constraint(op.f('uq_oarepo_oai_mapper_address'), 'oarepo_oai_mapper', type_='unique')
    # ### end Alembic commands ###
