#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Added OAIMapper table"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a0ccc82bae06'
down_revision = '24445d202733'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oarepo_oai_mapper',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('address', sa.String(length=2048), nullable=True),
                    sa.Column('rule_id', sa.Integer(), nullable=True),
                    sa.Column('parser_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['parser_id'], ['oarepo_oai_parser.id'], name=op.f(
                        'fk_oarepo_oai_mapper_parser_id_oarepo_oai_parser')),
                    sa.ForeignKeyConstraint(['rule_id'], ['oarepo_oai_rule.id'], name=op.f(
                        'fk_oarepo_oai_mapper_rule_id_oarepo_oai_rule')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_oarepo_oai_mapper')),
                    sa.UniqueConstraint('address', name=op.f('uq_oarepo_oai_mapper_address'))
                    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oarepo_oai_mapper')
    # ### end Alembic commands ###
