#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Initial revision."""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd31c01218315'
down_revision = 'd1bc58ae9793'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nrthesesmetadata_metadata',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nrthesesmetadata_metadata'))
    )
    op.create_table('nrthesesmetadata_metadata_version',
    sa.Column('created', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), autoincrement=False, nullable=True),
    sa.Column('updated', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), autoincrement=False, nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_nrthesesmetadata_metadata_version'))
    )
    op.create_index(op.f('ix_nrthesesmetadata_metadata_version_end_transaction_id'), 'nrthesesmetadata_metadata_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_nrthesesmetadata_metadata_version_operation_type'), 'nrthesesmetadata_metadata_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_nrthesesmetadata_metadata_version_transaction_id'), 'nrthesesmetadata_metadata_version', ['transaction_id'], unique=False)
    op.drop_index('ix_uq_partial_files_object_is_head', table_name='files_object')
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_uq_partial_files_object_is_head', 'files_object', ['bucket_id', 'key'], unique=False)
    op.drop_index(op.f('ix_nrthesesmetadata_metadata_version_transaction_id'), table_name='nrthesesmetadata_metadata_version')
    op.drop_index(op.f('ix_nrthesesmetadata_metadata_version_operation_type'), table_name='nrthesesmetadata_metadata_version')
    op.drop_index(op.f('ix_nrthesesmetadata_metadata_version_end_transaction_id'), table_name='nrthesesmetadata_metadata_version')
    op.drop_table('nrthesesmetadata_metadata_version')
    op.drop_table('nrthesesmetadata_metadata')
    # ### end Alembic commands ###
