#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Added default_endpoint field"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c5f7c2ec13'
down_revision = '10c95d1d9958'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oarepo_oai_provider', sa.Column('default_endpoint', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oarepo_oai_provider', 'default_endpoint')
    # ### end Alembic commands ###
