#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Added traceback column to OAIRecord table"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a53e55796fa'
down_revision = '5e003513e795'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oarepo_oai_record', sa.Column('traceback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oarepo_oai_record', 'traceback')
    # ### end Alembic commands ###
