#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Delete logs"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf8cd5988d6'
down_revision = '130a8df86799'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oarepo_oai_sync', 'logs')
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oarepo_oai_sync', sa.Column('logs', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
