#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""2021-01-14: oai_identifer in oai_record is not obligatory field anymore, it is preparation for
full deletion"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efc291af2039'
down_revision = '182e0f31cabc'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oarepo_oai_record', 'oai_identifier',
                    existing_type=sa.VARCHAR(length=2048),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oarepo_oai_record', 'oai_identifier',
                    existing_type=sa.VARCHAR(length=2048),
                    nullable=False)
    # ### end Alembic commands ###
